---
#______________________________________
# set cvmfs configuration files using j2 templates

- name: set cvmfs configuration files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: default.local.j2, dest: /etc/cvmfs/default.local }
    - { template: repository.conf.j2, dest: '/etc/cvmfs/config.d/{{ repository_name }}.conf' }
  when: repository_name != "data.galaxyproject.org"
#______________________________________
# download the required key.pub of the selected repository from github
# and paste it in the cvmfs key directory

- name: download repository public key from github
  get_url:
    url: 'https://raw.githubusercontent.com/indigo-dc/Reference-data-galaxycloud-repository/master/cvmfs_server_keys/{{ repository_name }}.pub'
    dest: '/etc/cvmfs/keys/{{ repository_name }}.pub'
  when: repository_name != "data.galaxyproject.org"

- name: set galaxy-yml configuration files
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: galaxy.yml.j2, dest: /etc/galaxy/galaxy.yml }
    - { template: mygalaxyenv.j2, dest: /etc/galaxy/.mygalaxyenv }
    - { template: delete_galaxy_user.py.j2, dest: /etc/galaxy/delete_galaxy_user.py } 
