---
##_____________________________________
#env file and script for user deletion that will be mounted in the docker

- name: set env file and delete galaxy-user
  template:
    src: '{{ item.template }}'
    dest: '{{ item.dest }}'
  with_items:
    - { template: mygalaxyenv.j2, dest: /etc/galaxy/.mygalaxyenv }
    - { template: delete_galaxy_user.py.j2, dest: /etc/galaxy/delete_galaxy_user.py } 
