---
#______________________________________
# galaxy dir creation that will contain the galaxydocker /export
# directory

- name: dirs creations galaxy and docker image
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ export_dir }}/galaxy"
    - "{{ export_dir }}/docker_image"
    - "/etc/proftpd"
    - "/etc/galaxy"

  ##_____________________________________
  ## docker_image dir creation that will contain docker images
  #
  #- name: docker_image dir creation
  #  file:
  #    path: "{{ export_dir }}/docker_image"
  #    state: directory

#______________________________________
# create the local cvmfs directory tree in order to mount cvmfs configuration
# files into galaxydocker

#- name: cvmfs local dir tree creation
#  file:
#    path: "{{ item.path }}"
#    state: "{{ item.state }}"
#  with_items:
#    - { path: /etc/cvmfs/default.d , state: directory }
#    - { path: /etc/cvmfs/keys , state: directory }
#    - { path: /etc/cvmfs/config.d , state: directory }
#  when: refdata_cvmfs_repository_name != "data.galaxyproject.org"

#- name: Set proftpd config dir
#  file:
#    path: /etc/proftpd
#    state: directory

- name: Copy proftpd configuration file
  template:
    src: 'proftpd.conf.j2'
    dest: '/etc/proftpd/proftpd.conf'

