---
#______________________________________
# galaxy dir creation that will contain the galaxydocker /export
# directory

- name: dirs creations galaxy and docker image
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ export_dir }}/galaxy"
    - "{{ export_dir }}/docker_image"
    - "/etc/proftpd"
    - "/etc/galaxy"

#_____________________________________
#set proftp configuration file

- name: Copy proftpd configuration file
  template:
    src: 'proftpd.conf.j2'
    dest: '/etc/proftpd/proftpd.conf'

