---

#______________________________________
# set galaxy_docker_flag from  GALAXY_VERSION variable

#- name: Get Galaxy version number for docker flag
#  set_fact:
#    galaxy_docker_flag: "{{ GALAXY_VERSION | replace('release_','') }}"

#______________________________________
# run galaxy docker mounting /export dir and cvmfs config files
# both for ansible version >2.4 and <2.4

- name: "galaxy docker run for default cvmfs configuration:TASK specific for ansible >2.4"
  docker_container:
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/etc/galaxy/delete_galaxy_user.py:rw"
      - "/etc/galaxy/galaxy.yml:/etc/galaxy/galaxy.yml:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
  when: ansible_version.full >= "2.4.0.0"

- name: "installation of docker-py and galaxy docker run run for default cvmfs configuration :TASK specific for ansible <2.4"
  docker: 
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/etc/galaxy/delete_galaxy_user.py/:rw"
      - "/etc/galaxy/galaxy.yml:/etc/galaxy/galaxy.yml:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
  when: ansible_version.full < "2.4.0.0"
