---

#______________________________________
# run galaxy docker mounting /export dir and cvmfs config files
# both for ansible version >2.4 and <2.4

- name: "[ansible >= 2.4] Galaxy Docker run (with tool_data_table mod)."
  docker_container:
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/opt/delete_galaxy_user.py:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
    #      - "/etc/cvmfs/keys/{{ refdata_cvmfs_repository_name }}.pub:/etc/cvmfs/keys/{{ refdata_cvmfs_repository_name }}.pub:rw"
    #      - "/etc/cvmfs/default.local:/etc/cvmfs/default.local:rw"
    #      - "/etc/cvmfs/config.d:/etc/cvmfs/config.d:rw"
    #      - "/etc/galaxy/tool_data_tables:/etc/galaxy/tool_data_tables:rw"
      - "/cvmfs:/cvmfs:shared"
  when: ansible_version.full >= "2.4.0.0"

