---

#______________________________________
# run galaxy docker mounting /export dir and cvmfs config files

- name: "ANSIBLE 2.9 Galaxy Docker run:"
  docker_container:
    name: galaxydocker
    image: "{{ galaxy_flavor }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
    detach: yes
    privileged: yes
    env_file: "/etc/galaxy/.mygalaxyenv"
    volumes:
      - "/etc/galaxy/delete_galaxy_user.py:/opt/delete_galaxy_user.py:rw"
      - "{{ export_dir }}/galaxy:{{ export_dir }}:rw"
      - /cvmfs:/cvmfs:shared
      - /etc/cvmfs:/etc/cvmfs:rw

