---

#______________________________________
# set galaxy_docker_flag from  GALAXY_VERSION variable

- name: Get Galaxy version number only for comparison
  set_fact:
    galaxy_docker_flag: "{{ GALAXY_VERSION | replace('release_','') }}"

#______________________________________
# run galaxy docker mounting /export dir and cvmfs config files
# both for ansible version >2.4 and <2.4

- name: "galaxy docker run :TASK specific for ansible >2.4"
  docker_container:
    name: galaxydocker
    image: "{{ galaxy_flavour }}:{{ galaxy_docker_flag }}"
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env: GALAXY_CONFIG_FILE={{galaxy_config_path}}/galaxy.yml
    volumes:
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
      - "/etc/cvmfs/keys/{{ repository_name }}.pub:/etc/cvmfs/keys/{{ repository_name }}.pub:rw"
      - "/etc/cvmfs/default.local:/etc/cvmfs/default.local:rw"
      - "/etc/cvmfs/config.d:/etc/cvmfs/config.d:rw"
  when: ansible_version.full >= "2.4.0.0"

- name: "installation of docker-py and galaxy docker run :TASK specific for ansible <2.4"
  docker: 
    name: galaxydocker
    image: "{{ galaxy_flavour }}:{{ galaxy_docker_flag }}" 
    state: started
    ports:
      - "80:80"
      - "21:21"
      - "22:22"
    detach: yes
    privileged: yes
    env: GALAXY_CONFIG_FILE={{galaxy_config_path}}/galaxy.yml
    volumes:
      - "{{ export_dir }}/galaxy:{{ export_dir }}/:rw"
      - "/etc/cvmfs/keys/{{ repository_name }}.pub:/etc/cvmfs/keys/{{ repository_name }}.pub:rw"
      - "/etc/cvmfs/default.local:/etc/cvmfs/default.local:rw"
      - "/etc/cvmfs/config.d:/etc/cvmfs/config.d:rw"
  when: ansible_version.full < "2.4.0.0"
