---

#______________________________________
#install a specific docker-py packages to fix docker_run.yml task
#for ansible version <2.4.0.0

- name: Install docker-py
  pip: 
    name: docker-py>=1.7.0
  when: ansible_version.full < "2.4.0.0"
