---

- name: Get docker config path number only for comparison
  set_fact:
    galaxy_local_config_path: "{{ galaxy_config_path | replace('/export','/export/galaxy') }}"



#______________________________________
#modify galaxy.yml file in order to set administrator credentials

- name: stat docker_sample
  stat: 
    path: "{{ galaxy_local_config_path }}/galaxy.yml.docker_sample"
  register: galaxydockerconf


- name: rename galaxy-yml
  command: mv {{ galaxy_local_config_path }}/galaxy.yml.docker_sample {{ galaxy_local_config_path }}/galaxy.yml
  when: galaxydockerconf.stat.exists == True

- name: stat galaxy-yml
  stat:
    path: "{{ galaxy_local_config_path }}/galaxy.yml"
  register: galaxyconf

- name: Set galaxyYML parameters
  lineinfile:
    dest: "{{ galaxy_local_config_path }}/galaxy.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: ' #admin_users: null', line: '  admin_users: {{ GALAXY_ADMIN_EMAIL }}' }
    - { regexp: ' #brand: null', line: '  brand: {{ galaxy_instance_description }}' }
  when: galaxyconf.stat.exists == True

#_____________________________________
# restart galaxy inside docker using supervisorctl

- name: restart galaxy 
  become_user: root
  command: docker exec galaxydocker /bin/bash -c "supervisorctl restart galaxy:"
  when: galaxyconf.stat.exists == True
