---
#_____________________________________
#run delete user python script

- name: delete-user 
  command: >
   docker exec galaxydocker /bin/bash -c 
   ". $GALAXY_VIRTUAL_ENV/bin/activate &&
   python /opt/delete_galaxy_user.py
   -u admin@galaxy.org -c /etc/galaxy/galaxy.yml "

#_____________________________________
# Set password

- name: Set Password from vault
  set_fact:
    GALAXY_ADMIN_PASSWORD: '{{ vault_secrets.data.admin_password }}'
  no_log: True
  when: retrieve_passphrase_from_vault

- name: Create random admin user api key
  set_fact:
    GALAXY_ADMIN_API_KEY: "{{ lookup('password', '/dev/null length=50') }}"
  no_log: True
  when: galaxy_admin_api_key == "random"

- name: Set custom admin user api key
  set_fact:
    GALAXY_ADMIN_API_KEY: "{{ galaxy_admin_api_key }}"
  no_log: True
  when: galaxy_admin_api_key != "random"

#_____________________________________
#run create user python script

- name: user creation 
  command: >
   docker exec galaxydocker /bin/bash -c ". $GALAXY_VIRTUAL_ENV/bin/activate
   && python /usr/local/bin/create_galaxy_user.py 
   --user {{ GALAXY_ADMIN_EMAIL }} --password {{ GALAXY_ADMIN_PASSWORD }}
   -c $GALAXY_CONFIG_FILE  --key {{ GALAXY_ADMIN_API_KEY }} && deactivate "

#_____________________________________
#test if there is the wf directory

- name: test workflow directory
  command: docker exec galaxydocker /bin/bash -c "test -d /home/galaxy/workflows "
  failed_when: false
  changed_when: false
  register: testdir
  ignore_errors: yes

#_____________________________________
#share workflow with admin user

- name: share wf
  command: >
    docker exec galaxydocker /bin/bash -c ". $GALAXY_VIRTUAL_ENV/bin/activate 
    && workflow-install --workflow_path $GALAXY_HOME/workflows/ 
    -g http://localhost:80 -u {{ GALAXY_ADMIN_EMAIL }} -p {{ GALAXY_ADMIN_PASSWORD }} "
  when: testdir.rc == 0

