---
#______________________________________
# mount cvmfs repository selected running cvmfs_config in the container

- name: load cvmfs repository
  become: true
  become_user: root
  shell: docker exec galaxydocker cvmfs_config probe
