---
#______________________________________
#task files for ansible-role-laniakea-docker

- include: dir_creation.yml

#- include: docker_tool_data.yml

- include: client_config.yml 

- include: prerequisites.yml

- include: docker_run_default.yml

- include: wait_galaxy_web.yml

- include: galaxy-yml-config.yml
