---

#______________________________________
# wait for galaxy docker to be accessible by browser

- name: wait until galaxy web is avaiable
  uri:
    url: "http://localhost:80"
    status_code: 200
  register: result 
  until: result.status == 200
  retries: 2000 
  delay: 1

